<?php
//CON ESTE COMANDO $_SERVER PODEMOS VER TODAS LAS VARIABLES DE SERVIDOR
//Y PODEMOS ACCEDER A URL PREVIAS, RUTAS PATH, IP ALGUNA INFORMACION IMPORTANTE ACERCA DE LA SESION DEL SERVIDOR

//HTTP_REFERER SIRVE PARA SABER DE DONDE VIENE EL USUARIO
/*ES IMPORTANTE POR QUE CON ELLO PODEMOS HACER UN REDIRECCION DE DONDE SE ENCONTRABA
EL USUARIO SI LLEGA A EJECUTAR UN LOGIN POR EJEMPLO DE CUALQUIER PAGINA
SIEMPRE LLEGARA A LA REFER URL SI ASI LA DEFINIMOS*/