<?php
//E_ERROR, ERROR GRAVE O FATAL ERROR, DETIENE LA EJECUCION DEL SCRIPT DONDE SUCEDE EL ERROR
//E_WARNING, ERROR LEVEL NON-FATAL ERROR, MUESTRAN EL MENSAJE Y SIGUEN EJECUTANDO EL SCRIPT
//E_PARSE, ERROR DE SINTAXIS O PARSEO, MAS COMUN OLVIDAR PUNTO Y COMO, DETIENE LA EJECUCION DEL SCRIPT
//E_NOTICE, AVISO DEL INTERPRETE PHP, POR EJEMPLO VARIABLES NO INICIALIZADAS O VACIAS, FUNCIONES DESPRECIADAS, NO DETIENE LA EJECUCION DEL SCRIPT

//habilitar errores en php.ini
//error_reporting = E_ALL
//displat_errors = On
//o habilitarlo por cada archivo de programacion
//ini_set('display_errors', 1); //habilitar en local
//error_reporting(E_ALL); //habilitar en local



// E_CORE_ERROR, ERROR DE PHP, DETIENE LA EJECUCION DEL SCRIPT
// E_CORE_WARNING, ADVERTENCIA DE PHP, NO DETIENE LA EJECUCION DEL SCRIPT
